<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Soflomo\Portfolio\Module'                               => __DIR__ . '/Module.php',
    'Soflomo\Portfolio\Repository\Item'                      => __DIR__ . '/src/Soflomo/Portfolio/Repository/Item.php',
    'Soflomo\Portfolio\View\Helper\Slug'                     => __DIR__ . '/src/Soflomo/Portfolio/View/Helper/Slug.php',
    'Soflomo\Portfolio\Exception\ItemNotFoundException'      => __DIR__ . '/src/Soflomo/Portfolio/Exception/ItemNotFoundException.php',
    'Soflomo\Portfolio\Exception\PortfolioNotFoundException' => __DIR__ . '/src/Soflomo/Portfolio/Exception/PortfolioNotFoundException.php',
    'Soflomo\Portfolio\Exception\InvalidArgumentException'   => __DIR__ . '/src/Soflomo/Portfolio/Exception/InvalidArgumentException.php',
    'Soflomo\Portfolio\Options\ModuleOptions'                => __DIR__ . '/src/Soflomo/Portfolio/Options/ModuleOptions.php',
    'Soflomo\Portfolio\Controller\ItemController'            => __DIR__ . '/src/Soflomo/Portfolio/Controller/ItemController.php',
    'Soflomo\Portfolio\Entity\ItemInterface'                 => __DIR__ . '/src/Soflomo/Portfolio/Entity/ItemInterface.php',
    'Soflomo\Portfolio\Entity\PortfolioBase'                 => __DIR__ . '/src/Soflomo/Portfolio/Entity/PortfolioBase.php',
    'Soflomo\Portfolio\Entity\Item'                          => __DIR__ . '/src/Soflomo/Portfolio/Entity/Item.php',
    'Soflomo\Portfolio\Entity\ItemBase'                      => __DIR__ . '/src/Soflomo/Portfolio/Entity/ItemBase.php',
    'Soflomo\Portfolio\Entity\Portfolio'                     => __DIR__ . '/src/Soflomo/Portfolio/Entity/Portfolio.php',
    'Soflomo\Portfolio\Entity\PortfolioInterface'            => __DIR__ . '/src/Soflomo/Portfolio/Entity/PortfolioInterface.php',
    'Soflomo\PortfolioAdmin\Service\Item'                    => __DIR__ . '/src/Soflomo/PortfolioAdmin/Service/Item.php',
    'Soflomo\PortfolioAdmin\Form\Item'                       => __DIR__ . '/src/Soflomo/PortfolioAdmin/Form/Item.php',
    'Soflomo\PortfolioAdmin\Controller\ItemController'       => __DIR__ . '/src/Soflomo/PortfolioAdmin/Controller/ItemController.php',
);