<?php
/**
 * Edit page of portfolio item in admin
 *
 * @var $portfolio Current portfolio
 * @var $item      Item from this portfolio
 * @var $form      Form to edit item
 */
?>

<h1>Edit item</h1>

<?php $form->prepare()?>
<?php echo $this->form()->openTag($form)?>
    <?php echo $this->formRow($form->get('title'))?>
    <?php echo $this->formRow($form->get('lead')->setAttributes(array(
        'cols' => 50,
        'rows' => 10,
    )))?>
    <?php echo $this->formRow($form->get('body')->setAttributes(array(
        'cols' => 50,
        'rows' => 10,
    )))?>
    <button type="submit">Save</button>
<?php echo $this->form()->closeTag()?>