<?php
/**
 * Listing of portfolio categories in admin
 *
 * @var $portfolio  Current portfolio
 * @var $categories Categories
 */
?>

<h1>Category listing</h1>

<a href="<?php echo $this->url('zfcadmin/portfolio/category/create', array(), array(), true)?>">
    New category
</a>

<?php if (count($categories)): ?>
<ul>
<?php foreach ($categories as $category): ?>
    <li><a href="<?php echo $this->url('zfcadmin/portfolio/category/view', array(
        'category' => $category->getId(),
    ), array(), true)?>">
        <?php echo $this->escapeHtml($category->getName())?>
    </a></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
