<?php
/**
 * Edit page of portfolio category in admin
 *
 * @var $portfolio Current portfolio
 * @var $category  Category from this portfolio
 * @var $form      Form to edit category
 */
?>

<h1>Edit category</h1>

<?php $form->prepare()?>
<?php echo $this->form()->openTag($form)?>
    <?php echo $this->formRow($form->get('slug'))?>
    <?php echo $this->formRow($form->get('name'))?>
    <button type="submit">Save</button>
<?php echo $this->form()->closeTag()?>
