<?php
/**
 * (Pre)view page of portfolio category in admin
 *
 * @var $portfolio Current portfolio
 * @var $category  Category from this portfolio
 */
?>

<ul>
    <li><a href="<?php echo $this->url('zfcadmin/portfolio/category', array(), array(), true)?>">Back to listing</a></li>
    <li><a href="<?php echo $this->url('zfcadmin/portfolio/category/update', array(), array(), true)?>">Edit this category</a></li>
</ul>

<article>
    <p><?php echo $this->escapeHtml($category->getName())?></p>
</article>
